openapi: 3.0.3
info:
  title: People Manager
  description: |-
    Este e um projeto para fins educacionais e teste dos conhecimentos
  contact:
    email: sauloddiniz@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.11
servers:
  - url: http://localhost:8080/api
tags:
  - name: person
    description: description by person
  - name: address
    description: address person
paths:
  /person:
    put:
      tags:
        - person
      summary: Update an existing person
      description: Update an existing person by Id
      operationId: updatePerson
      requestBody:
        description: Update an existent person
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Person'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Person'
        '400':
          description: Invalid ID supplied
        '404':
          description: Person not found
        '422':
          description: Validation exception
    post:
      tags:
        - person
      summary: Add a new person
      description: Add a new person
      operationId: addPerson
      requestBody:
        description: Create a person
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Person'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Person'
        '400':
          description: Invalid input
        '422':
          description: Validation exception

components:
  schemas:
    Person:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 10
        personId:
          type: integer
          format: int64
          example: 1
        fullName:
          type: string
        birthDate:
          type: string
          format: date-time
    Address:
      type: object
      properties:
        addressId:
          type: integer
          format: int64
          example: 1
        street:
          type: string
          example: Duque de Caxias
        city:
          type: string
          example: Coronel Fabriciano
        state:
          type: string
          example: MG
        CEP:
          type: string
          example: '35170-009'
        isPrincipal:
          type: boolean
          example: true