openapi: 3.0.3
info:
  title: People Manager
  description: |-
    Este e um projeto para fins educacionais e teste dos conhecimentos
  contact:
    email: sauloddiniz@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.11
servers:
  - url: http://localhost:8080/api
tags:
  - name: person
    description: description by person
  - name: address
    description: address person
paths:
  /person:
    post:
      tags:
        - person
      summary: Add a new person
      description: Add a new person
      operationId: addPerson
      requestBody:
        description: Create a person
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PersonRequestDto'
        required: true
      responses:
        '201':
          description: created
          headers:
            Location:
              description: URI location created by person
              schema:
                type: string
        '400':
          description: bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
    get:
      tags:
        - person
      summary: List person
      description: list all person
      operationId: listPerson
      parameters:
        - name: names
          in: query
          description: List of names to filter the persons
          required: false
          schema:
            type: array
            items:
              type: string
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PersonResponseDto'
        '500':
          description: Internal server error
  /person/{id}:
    put:
      tags:
        - person
      summary: Update an existing person
      description: Update an existing person by Id
      operationId: updatePerson
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: The ID of the person to be updated
      requestBody:
        description: Update an existent person
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PersonRequestDto'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PersonRequestDto'
        '204':
          description: Person not found
        '500':
          description: Internal server error
components:
  schemas:
    PersonRequestDto:
      type: object
      required:
        - fullName
        - birthDate
      properties:
        fullName:
          type: string
        birthDate:
          type: string
          format: date
    PersonResponseDto:
      type: object
      properties:
        fullName:
          type: string
        birthDate:
          type: string
          format: date
    Address:
      type: object
      properties:
        addressId:
          type: integer
          format: int64
          example: 1
        street:
          type: string
          example: Duque de Caxias
        city:
          type: string
          example: Coronel Fabriciano
        state:
          type: string
          example: MG
        CEP:
          type: string
          example: '35170-009'
        isPrincipal:
          type: boolean
          example: true
    ErrorResponse:
      type: object
      properties:
        date:
          type: string
          format: Wed May 08 00:00:00 BRT 2024
        status:
          type: int
          example: 400
        path:
          type: string
          example: /person
        message:
          type: string
          example: Error field
        method:
          type: string
          example: POST